const fs = require('node:fs');
const path = require('node:path');
const { root, loadCountries } = require('./lib/data.cjs');
const read = file => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8'));
const write = (file, value) => fs.writeFileSync(path.join(root, file), JSON.stringify(value, null, 2) + '\n');
const countries = loadCountries();
const original = new Map(read('audit/original-countries.json').map(c => [c.code, c]));
const corrections = read('audit/corrections.json');
const questions = read('audit/open-questions.json');
const wb = read('audit/sources/world-bank-population-2024.json');
const wbRows = new Map(wb.response[1].map(r => [r.country.id, r]));
const un = read('audit/sources/un-country-profiles-2026-09-07.json');
const iso = read('audit/sources/iso-4217-provenance-2026-09-07.json');
const checkedAt = '2026-09-07';
const labels = { capital: 'בירה', currency: 'מטבע', languages: 'שפות נבחרות', hello: 'משמעות הברכה ושפתה', 'representative.descriptionHe': 'תיאור', 'representative.titleHe': 'שם הסמל', funFactHe: 'עובדה מעניינת' };
const get = (object, field) => field.split('.').reduce((value, key) => value?.[key], object);

const populationComparison = countries.map(c => {
  const before = original.get(c.code).population;
  const reference = wbRows.get(c.code).value;
  return { code: c.code, name: c.nameEn, original2024: before.value, reference2024: reference,
    deviationPercent: Number(((before.value - reference) / reference * 100).toFixed(3)), current: c.population };
});
write('audit/population-comparison.json', populationComparison);
write('audit/changes.json', corrections.map(row => ({ ...row, original: get(original.get(row.code), row.field), current: get(countries.find(c => c.code === row.code), row.field) })));

const sourceIndex = {};
const reviews = countries.map(c => {
  const profile = un.profiles.find(p => p.countryCode === c.code);
  if (!profile || profile.httpStatus !== 200) throw new Error(`Missing UN reference for ${c.code}`);
  const changes = corrections.filter(row => row.code === c.code);
  sourceIndex[c.code] = [{ fields: ['capital', 'currency'], label: 'השוואת בירה ומטבע', title: 'UNdata — מהדורת 2025', url: profile.url, checkedAt,
    note: 'השוואה למהדורת 2025; אינה אישור שכל הנתונים עדכניים ל־2026.' },
    { fields: ['currency.code'], label: 'קוד מטבע', title: 'SIX / ISO 4217', url: iso.url, checkedAt, note: 'קיום הקוד ברשימה אינו בדיקה מלאה של כל המטבעות הנמצאים בשימוש במדינה.' },
    ...changes.map(row => ({ fields: [row.field], label: labels[row.field] || row.field, title: row.title, url: row.url, checkedAt: row.checkedAt,
      note: row.field === 'hello' ? 'המקור תומך בשפה ובמשמעות; התעתיק העברי עדיין דורש בדיקת הגייה.' : '' }))];
  if (['GE', 'CY'].includes(c.code)) sourceIndex[c.code].push({ fields: ['continent'], label: 'סיווג יבשת', title: 'UN M49', url: 'https://unstats.un.org/unsd/methodology/m49/', checkedAt, note: 'באוסף זה המדינה משויכת לאירופה. בסיווג הסטטיסטי של האו״ם היא במערב אסיה. סיווגים שונים משרתים מטרות שונות.' });
  if (c.code === 'IL') sourceIndex[c.code][0].note += ' UNdata מציין כי הגדרת ירושלים כבירה נמסרה בידי ישראל; עמדת האו״ם מפורטת בהחלטותיו.';
  const contentFields = ['representative.descriptionHe', 'funFactHe'];
  return { code: c.code, nameHe: c.nameHe, population: { status: 'matched-source', year: c.population.year, sourceUrl: c.population.sourceUrl },
    capital: { status: changes.some(r => r.field === 'capital') ? 'clarified-with-source' : 'cross-checked-2025-profile', sourceUrl: profile.url },
    currency: { status: changes.some(r => r.field === 'currency') ? 'corrected-or-clarified-with-source' : 'cross-checked-profile-and-code-list', legalTenderExhaustivelyVerified: false },
    languages: { status: changes.some(r => r.field === 'languages') ? 'selected-list-supported' : 'screened-not-externally-verified', exhaustive: false },
    greeting: { status: changes.some(r => r.field === 'hello') ? 'meaning-and-language-supported' : 'screened-not-externally-verified', hebrewPronunciationVerified: false },
    content: Object.fromEntries(contentFields.map(field => [field, changes.some(r => r.field === field) ? 'corrected-with-source' : 'screened-not-externally-verified'])),
    openQuestions: questions.filter(q => q.code === c.code) };
});
write('audit/review-status.json', { checkedAt, countries: reviews });
const reviewNotes = Object.fromEntries(countries.map(c => [c.code, questions.filter(q => q.code === c.code)]));
fs.writeFileSync(path.join(root, 'data/sources.js'), '// Generated by npm run audit. Edit audit/corrections.json and source snapshots instead.\nwindow.COUNTRY_SOURCES = ' + JSON.stringify(sourceIndex, null, 2) + ';\nwindow.COUNTRY_REVIEW_NOTES = ' + JSON.stringify(reviewNotes, null, 2) + ';\n');

const bigGaps = populationComparison.filter(r => Math.abs(r.deviationPercent) > 5).sort((a, b) => Math.abs(b.deviationPercent) - Math.abs(a.deviationPercent));
const contentCount = corrections.filter(r => ['representative.descriptionHe', 'funFactHe'].includes(r.field)).length;
const text = value => typeof value === 'string' ? value : JSON.stringify(value);
const cell = value => text(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const report = `# בדיקת אמינות ושיפור — מדינות העולם

תאריך הבדיקה: ${checkedAt}. קהל יעד: בעל הפרויקט ועורכי התוכן. היקף: כל ${countries.length} הרשומות הקיימות.

## התוצאה

עודכנו נתוני האוכלוסייה של כל ${countries.length} המדינות לאומדני אמצע שנת 2025 של הבנק העולמי. בוצעו ${corrections.length} תיקונים והבהרות בשדות נוספים, מהם ${contentCount} בתיאורים ובעובדות מעניינות. נוסף תיעוד מקורות בכל כרטיס, חיפוש בעברית ובאנגלית, תצוגת שנה לצד אוכלוסייה, הבהרת יחידת שער החליפין ותאריך השער, והתאמה למסך צר.

זו ביקורת מקיפה של האוסף, אך אינה אישור שכל משפט בו אומת. כל 300 שדות התיאור והעובדה נקראו ונסרקו; ${contentCount} שדות תוכן תוקנו על סמך מקורות. שאר שדות התוכן מסומנים במפורש ככאלה שטרם אומתו מול מקור חיצוני. כל 150 התעתיקים העבריים עדיין דורשים בדיקת דובר או בלשן, וגם ניקוד הטקסטים החדשים אינו אישור לשוני מקצועי.

## אוכלוסייה: השוואה הוגנת בין שנים

תחילה הושוו המספרים הישנים, שסומנו 2024, לנתוני 2024 מאותו מקור. ב־${bigGaps.length} מדינות הפער המוחלט גדול מ־5%. זהו פער ביחס לסדרה שנבחרה, לא בהכרח הוכחה לטעות: הגדרות תושבות, שטח, תאריכי מפקד ותיקוני אומדנים עשויים להשתנות בין מקורות.

לאחר מכן עודכנו הכרטיסים לשנת 2025, הזמינה לכל האוסף. שני העותקים נשמרו ב־sources, כולל כתובת הבקשה, תאריך המשיכה ותאריך עדכון המאגר (2026-07-13). שינוי מ־2024 ל־2025 אינו נחשב לתיקון טעות של השנה הקודמת.

המקור הוא [World Bank SP.POP.TOTL](https://data.worldbank.org/indicator/SP.POP.TOTL). לפי [הגדרת המדד](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/SP.POP.TOTL), אלו אומדני אמצע שנה של תושבים; הם אינם ספירה בזמן אמת. נתוני המקור נשמרים במספרים מלאים, ובכרטיס מוצג עיגול לצורכי קריאה. שימוש בנתוני הבנק העולמי כפוף ל־[CC BY 4.0 ולתנאי המאגר](https://datacatalog.worldbank.org/int/public-licenses#cc-by).

| מדינה | נתון ישן (2024) | מקור אחיד (2024) | פער ביחס למקור |
| --- | ---: | ---: | ---: |
${bigGaps.map(r => `| ${r.name} (${r.code}) | ${r.original2024.toLocaleString('en-US')} | ${r.reference2024.toLocaleString('en-US')} | ${r.deviationPercent.toFixed(1)}% |`).join('\n')}

## בירות, מטבעות ושפות

נמשכו בהצלחה כל 150 פרופילי UNdata, מהדורת 2025, כולל הערות השוליים. שמות הבירות הקיימים תואמים לאחר התחשבות בכתיב; התאמה כזו אינה מספיקה כאשר הערת השוליים מבדילה בין בירה חוקתית, מחוקקת ומושב ממשלה. נוספו הבהרות לדרום אפריקה, סרי לנקה, בוליביה, הולנד, מלזיה, חוף השנהב ושווייץ.

149 מתוך 150 קודי המטבע המקוריים נמצאו ברשימת SIX העדכנית שנשמרה. החריג BGN הוחלף ב־EUR לפי [הבנק המרכזי האירופי](https://www.ecb.europa.eu/euro/changeover/bulgaria/html/index.en.html). הרשימה מאשרת קודים; היא אינה לבדה בדיקה מלאה של כל הסדרי ההילך החוקי. בפנמה נוסף אזכור של בלבואה לצד דולר. VES בוונצואלה ו־ZWG בזימבבואה לא הוחלפו: הם קיימים ברשימה. פרופיל UNdata הישן אינו גובר על מקור חדש וממוקד.

בירת אינדונזיה נשארה ג׳קרטה: [רשות נוסנטרה ביולי 2026](https://ikn.go.id/id/posts/pembangunan-tahap-ii-ikn-terus-berjalan-otorita-ikn-lakukan-evaluasi-berkala) מתארת יעד לבירה פוליטית ב־2028. במהלך הבדיקה לא נמצאה ראיה מספקת להעברה משפטית שכבר נכנסה לתוקף. אסטנה נשארה ללא שינוי. ירושלים נשארה עם הערת ההקשר שבמקור UNdata.

כותרת השפות שונתה ל״שפות (מבחר)״: האוסף אינו מנסה למנות את כל השפות בכל מדינה. נוספו שפות בסינגפור, בלגיה, פינלנד, שווייץ, רואנדה ופיג׳י. כותרת הברכה שונתה ל״ברכה מקומית״, משום שחלק מהברכות פירושן ״ברוכים הבאים״ או ״מה שלומך״. בשבע מדינות נוספו משמעות ושפה או תוקן הטקסט; התעתיק אינו מסומן כמאומת.

## כיסוי וסיווג

האוסף מכיל 150 רשומות, ולא רשימה מלאה של מדינות העולם. לצורך קנה מידה, [באו״ם 193 מדינות חברות](https://www.un.org/en/about-us). לא נוספו מדינות אוטומטית בלי כתיבת תוכן ובדיקתו. הכיסוי לפי הקבצים: אסיה 43, אירופה 45, אפריקה 30, צפון אמריקה 14, דרום אמריקה 12 ואוקיאניה 6.

גאורגיה וקפריסין נשארו באירופה בהתאם לבחירת האוסף; נוספה הערה שהן במערב אסיה לפי [UN M49](https://unstats.un.org/unsd/methodology/m49/). השתייכות סטטיסטית, גאוגרפית ותרבותית אינה תמיד זהה. מדינות חוצות יבשות דורשות הסבר ואינן שגיאת סכמה.

## יומן תיקונים והבהרות

הערכים המקוריים והחדשים המדויקים, הסבר הראיה ופרטי המקור נמצאים גם ב־[changes.json](changes.json).

| מדינה | שדה | הנוסח או הערך המעודכן | מקור |
| --- | --- | --- | --- |
${corrections.map(r => `| ${r.code} | ${labels[r.field] || r.field} | ${cell(r.replacement)} | [${cell(r.publisher)}](${r.url}) |`).join('\n')}

## פערים שדורשים המשך עריכה

בנוסף לשדות שטרם קיבלו מקור, אותרו ${questions.length} טענות ממוקדות לבירור. הן מועמדות לבדיקה, ואינן כולן טעויות מוכחות. לכל אחת נשמרו המדינה והשדה ב־[open-questions.json](open-questions.json).

${questions.map(q => `- **${q.code}** — ${q.reason}`).join('\n')}

מומלץ לתת קדימות לטענות ״היחיד״, ״הראשון״ ו״הגדול ביותר״; לנתונים מספריים ללא שנה; ולסמלים שמתוארים כרשמיים. כל רשומה ללא מקור נשארת פתוחה לבדיקת תוכן. הבדיקה נעצרה לאחר השלמת ההשוואות הרוחביות ותיקון הטענות שלהן נמצאו ראיות מספקות; הפערים אינם מוסתרים ואינם מסומנים כהצלחה.

## שיטה, שחזור ותחזוקה

המחקר כלל סריקה מלאה של הרשומות, השוואות API של הבנק העולמי, 150 פרופילי UNdata, רשימת ISO 4217 וחיפושים ממוקדים באתרי ממשלה, מוזיאונים, אוניברסיטאות, אונסק״ו וגופי תיירות רשמיים. ההעדפה היא למקור המתאים לטענה, לתאריך ולהגדרה. קישור שהפנה לעמוד כללי הוחלף במקור ישיר; כך, בטענת הדפוס נבחרה הספרייה הלאומית של צרפת.

אין בדוח טענה למעקב אוטומטי פעיל. בדיקות מקומיות אינן דורשות רשת. כדי לבדוק שינוי חיצוני בעתיד, יש למשוך עותק מועמד, להשוותו, ורק אז להחיל אותו. עותק מקור קיים אינו נדרס אוטומטית.

פקודות: <code>npm test</code>, <code>npm run validate</code>, <code>npm run check:population</code>, <code>npm run audit</code>. קובץ [review-status.json](review-status.json) מציג את מצב הבדיקה בכל מדינה ובכל משפחת שדות. תוצאות בדיקת הדפדפן וההדפסה מתועדות ב־[VERIFICATION.md](VERIFICATION.md).
`;
fs.writeFileSync(path.join(root, 'audit/REPORT.md'), report);
console.log(`Generated report, source index and review status: ${countries.length} countries, ${corrections.length} corrections, ${bigGaps.length} population gaps >5%.`);
